### ISSUE TITLE
Rails 4 File Sprockets::FileNotFound

### ISSUE THREAD

**Issue by davidreghay** [dnagir/spinjs-rails#13]
I get the error Sprockets::FileNotFound when adding

<code>//= require spin</code>

to my application.js in Rails 4

Anything I can do about this?

**Comment by dnagir** [comment]
The sprockets syntax to require files is:

```
//= require spin
```

(not the equal instead of slash).

Otherwise I'm not sure what the issue is.

**Comment by davidreghay** [comment]
Thanks for responding!  To my embarrassment, it was my own fault.  I simply forgot to restart the server.

Thanks again, and nice work!
